export const countriesFallback = [
  {
    country: "Australia",
    name: "Australia",
    slug: "australia",
    flag_url: "🇦🇺",
    description:
      "Australia is one of the world's most popular study destinations, offering globally recognised qualifications, a multicultural environment, and a Post-Study Work Visa of up to 4 years. It is home to 8 universities ranked in the global top 100.",
    cost_info: "AUD 20,000 – 50,000/year",
    visa_info: "Student Visa (Subclass 500) via Department of Home Affairs",
    image_url:
      "/assets/Australia.jpeg",
    tuition_fees: {
      undergraduate: { min: 20000, max: 50000, currency: "AU$" },
      postgraduate: { min: 22000, max: 55000, currency: "AU$" },
      mba: { min: 30000, max: 70000, currency: "AU$" },
      doctorate: { min: 25000, max: 45000, currency: "AU$" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.0" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.5", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.5", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.5", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "60", max_score: "79" },
      { test: "TOEFL", level: "Postgraduate", min_score: "79", max_score: "94" },
      { test: "TOEFL", level: "MBA", min_score: "79", max_score: "100" },
      { test: "TOEFL", level: "Doctorate", min_score: "79", max_score: "100" },
      { test: "PTE", level: "Undergraduate", min_score: "50", max_score: "58" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "72" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "72" },
    ],
    intakes: [
      { name: "February", term: "Term 1", apply_window: "October - November" },
      { name: "July", term: "Term 2", apply_window: "May - June" },
      { name: "November", term: "Term 3", apply_window: "September" },
    ],
    post_study_work_salary: [
      { field: "IT & Tech", min: 60000, max: 80000, currency: "AUD" },
      {
        field: "Business & Management",
        min: 65000,
        max: 85000,
        currency: "AUD",
      },
      { field: "Health & Medicine", min: 70000, max: 90000, currency: "AUD" },
      { field: "Engineering", min: 65000, max: 88000, currency: "AUD" },
    ],
    top_courses: [
      "Engineering",
      "Business and Management",
      "Information Technology",
      "Environmental Sciences",
      "Tourism and Hospitality",
      "Nursing",
      "STEM Courses",
      "Architecture & Construction",
      "Computer Science",
      "Commercial Pilot",
      "Public Health",
      "Juris Doctor",
      "Culinary Arts",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrolment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Police Clearance",
      "Statement of purposes",
    ],
    scholarships: [
      "Australia Awards Scholarships: PG/PhD - Full - https://www.dfat.gov.au/people-to-people/australia-awards-scholarships",
      "Australian Government Research Training Program (RTP): PG/PhD - Full - https://www.education.gov.au/research-block-grants/research-training-program",
      "Australian Development Scholarships (ADS): PG/PhD - Full - https://bangladesh.embassy.gov.au/daca/scholarships.html",
      "University of Sydney International Academic Excellence Scholarship: UG/PG - Full/Partial - https://www.sydney.edu.au/scholarships",
      "Bond University ADCO Sports Excellence Scholarship: UG/PG - Full - https://bond.edu.au/scholarship",
      "ECU Western Australian Premier's University Scholarship: UG/PG/PhD - Full/Partial - Contact us",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "UK",
    name: "UK",
    slug: "uk",
    flag_url: "🇬🇧",
    description:
      "The United Kingdom is home to some of the world's oldest and most prestigious universities including Oxford, Cambridge, and Imperial College London. The Graduate Route Visa allows 2 years post-study work rights, making it a top choice for career-driven students.",
    cost_info: "GBP 10,000 – 38,000/year",
    visa_info: "UK Student Visa via UKVI (formerly Tier 4)",
    image_url:
      "/assets/uk.jpeg",
    tuition_fees: {
      undergraduate: { min: 10000, max: 38000, currency: "£" },
      postgraduate: { min: 10000, max: 42000, currency: "£" },
      mba: { min: 15000, max: 65000, currency: "£" },
      doctorate: { min: 12000, max: 28000, currency: "£" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.5", max_score: "7.0" },
      { test: "IELTS", level: "MBA", min_score: "6.5", max_score: "7.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.5", max_score: "7.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "90", max_score: "100" },
      { test: "TOEFL", level: "MBA", min_score: "95", max_score: "105" },
      { test: "TOEFL", level: "Doctorate", min_score: "95", max_score: "105" },
      { test: "PTE", level: "Undergraduate", min_score: "56", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "61", max_score: "70" },
      { test: "PTE", level: "MBA", min_score: "65", max_score: "76" },
      { test: "PTE", level: "Doctorate", min_score: "65", max_score: "76" },
    ],
    intakes: [
      { name: "Autumn", term: "Term 1", apply_window: "September - December" },
      { name: "Winter", term: "Term 2", apply_window: "January - April" },
      { name: "Spring", term: "Term 3", apply_window: "April - June" },
      { name: "Summer", term: "Term 4", apply_window: "June - August" },
    ],
    post_study_work_salary: [
      {
        field: "Business Management / Statistics & Data Science",
        min: 70000,
        max: 70000,
        currency: "GBP",
      },
      {
        field: "Education and Training",
        min: 45000,
        max: 45000,
        currency: "GBP",
      },
      { field: "Healthcare", min: 51000, max: 51000, currency: "GBP" },
      {
        field: "IT & Computer Science",
        min: 65000,
        max: 65000,
        currency: "GBP",
      },
    ],
    top_courses: [
      "Law",
      "Medicine",
      "Engineering & Technology",
      "Sciences",
      "Architecture",
      "Business and Management",
      "Humanities",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "CAS Letter",
      "Recent Bank Statement",
      "All academic Certificates / Transcripts",
      "English Proficiency Certificate",
      "Tuberculosis Blood (TB) Test",
      "Health Surcharge",
      "Work Experience Letter (if applicable)",
    ],
    scholarships: [
      "Chevening: PG/PhD - Full - https://www.chevening.org",
      "Commonwealth Scholarships: PG/PhD - Full - https://study-uk.britishcouncil.org/scholarships-funding/commonwealth-scholarships",
      "Great Scholarships: PG - Partial - https://study-uk.britishcouncil.org/scholarships-funding/great-scholarships",
      "Clarendon Fund Scholarships: PG/PhD - Full - https://www.ox.ac.uk/admissions/graduate/fees-and-funding/funding/clarendon",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "USA",
    name: "USA",
    slug: "usa",
    flag_url: "🇺🇸",
    description:
      "The United States hosts the world's largest higher education system with over 4,000 accredited institutions. Home to Ivy League universities and Silicon Valley, the USA offers unparalleled research, innovation, and career networking opportunities for international students.",
    cost_info: "USD 8,000 – 75,000/year",
    visa_info: "F-1 Student Visa via US Embassy/Consulate",
    image_url:
      "https://images.unsplash.com/photo-1564309780826-cce2ef0705a0?q=80&w=1170&auto=format&fit=crop",
    tuition_fees: {
      undergraduate: { min: 8000, max: 75000, currency: "$" },
      postgraduate: { min: 8000, max: 80000, currency: "$" },
      mba: { min: 9000, max: 120000, currency: "$" },
      doctorate: { min: 9000, max: 35000, currency: "$" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "5.5", max_score: "7.0" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "7.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "7.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "7.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "55", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "55", max_score: "105" },
      { test: "TOEFL", level: "MBA", min_score: "58", max_score: "105" },
      { test: "TOEFL", level: "Doctorate", min_score: "58", max_score: "105" },
      { test: "PTE", level: "Undergraduate", min_score: "47", max_score: "67" },
      { test: "PTE", level: "Postgraduate", min_score: "52", max_score: "72" },
      { test: "PTE", level: "MBA", min_score: "56", max_score: "78" },
      { test: "PTE", level: "Doctorate", min_score: "56", max_score: "78" },
    ],
    intakes: [
      {
        name: "Fall",
        term: "Primary",
        apply_window: "December - February",
        start_month: "August/September",
      },
      {
        name: "Spring",
        term: "Secondary",
        apply_window: "August - October",
        start_month: "January/February",
      },
      {
        name: "Summer",
        term: "Limited",
        apply_window: "February - March",
        start_month: "May/June",
      },
    ],
    post_study_work_salary: [
      {
        field: "Business Management / Statistics & Data Science",
        min: 70000,
        max: 70000,
        currency: "USD",
      },
      {
        field: "Education and Training",
        min: 45000,
        max: 45000,
        currency: "USD",
      },
      { field: "Healthcare", min: 51000, max: 51000, currency: "USD" },
      {
        field: "IT & Computer Science",
        min: 65000,
        max: 65000,
        currency: "USD",
      },
    ],
    top_courses: [
      "Computer Science and Information Technology",
      "Engineering",
      "Data Science and Analytics",
      "Biotechnology and Life Sciences",
      "MBA",
      "Finance and Banking",
      "International Business",
      "Medicine and Healthcare",
      "Public Health",
      "Pharmacy and Biomedical Sciences",
    ],
    visa_documents: [
      "Passport",
      "I-20 Form from university",
      "DS-160 Application Confirmation Form",
      "SEVIS Payment Confirmation",
      "Bank Solvency proof",
      "All academic Transcripts & Certificates",
      "English Proficiency Certificate / SAT / GRE / GMAT (if applicable)",
    ],
    scholarships: [
      "Fulbright Foreign Student Program: PG/PhD - Full - https://foreign.fulbrightonline.org",
      "Knight-Hennessy Scholars: PG/PhD - Full - https://knight-hennessy.stanford.edu",
      "AAUW International Fellowships: UG/PG/PhD - Full - https://www.aauw.org/resources/programs/fellowships-grants/",
      "Humphrey Fellowship: PG/PhD - Full - https://www.humphreyfellowship.org",
      "Harvard University Scholarships: UG/PG/PhD - Full/Partial - https://college.harvard.edu/financial-aid",
      "Berea College Scholarships: UG - Full - https://college.harvard.edu/financial-aid",
      "IEFA (International Education Financial Aid): UG/PG/PhD - Full - iefa.org",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "Canada",
    name: "Canada",
    slug: "canada",
    flag_url: "🇨🇦",
    description:
      "Canada offers world-class education, multicultural cities, and one of the most welcoming immigration pathways for international students. With 700+ partner institutions across major provinces, it is a top destination for quality and affordability.",
    cost_info: "CAD 18,000 – 45,000/year",
    visa_info: "Student Direct Stream (SDS) or regular Study Permit via IRCC",
    image_url:
      "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=800",
    tuition_fees: {
      undergraduate: { min: 18000, max: 45000, currency: "CA$" },
      postgraduate: { min: 17000, max: 40000, currency: "CA$" },
      mba: { min: 25000, max: 80000, currency: "CA$" },
      doctorate: { min: 7000, max: 25000, currency: "CA$" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.5", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.5", max_score: "7.0" },
      { test: "IELTS", level: "Doctorate", min_score: "6.5", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Postgraduate", min_score: "88", max_score: "100" },
      { test: "TOEFL", level: "MBA", min_score: "90", max_score: "105" },
      { test: "TOEFL", level: "Doctorate", min_score: "90", max_score: "105" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "60", max_score: "68" },
      { test: "PTE", level: "MBA", min_score: "65", max_score: "76" },
      { test: "PTE", level: "Doctorate", min_score: "65", max_score: "76" },
    ],
    intakes: [
      {
        name: "Fall",
        term: "Primary",
        apply_window: "November - February",
        start_month: "September",
      },
      {
        name: "Winter",
        term: "Secondary",
        apply_window: "August - October",
        start_month: "January",
      },
      {
        name: "Summer",
        term: "Limited",
        apply_window: "February - March",
        start_month: "May",
      },
    ],
    post_study_work_salary: [
      {
        field: "IT & Computer Science",
        min: 65000,
        max: 90000,
        currency: "CAD",
      },
      { field: "Engineering", min: 60000, max: 85000, currency: "CAD" },
      {
        field: "Business & Management",
        min: 55000,
        max: 80000,
        currency: "CAD",
      },
      {
        field: "Healthcare & Nursing",
        min: 65000,
        max: 95000,
        currency: "CAD",
      },
    ],
    top_courses: [
      "Computer Science & IT",
      "Engineering",
      "Business Administration (MBA)",
      "Healthcare & Nursing",
      "Hospitality & Tourism",
      "Environmental Sciences",
      "Finance & Banking",
      "Data Science",
      "Architecture",
      "Public Health",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Enrollment confirmation",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Police Clearence",
      "Statement of purposes",
    ],
    scholarships: [
      "Vanier Canada Graduate Scholarships (Vanier CGS): PG/PhD - Full - https://vanier.gc.ca/en/eligibility-admissibilite.html",
      "International Major Entrance Scholarship (UBC): UG - Partial - https://you.ubc.ca/financial-planning/scholarships-awards-international-students/",
      "International Admission Scholarship (University of Alberta): UG - Partial - https://www.ualberta.ca/en/admissions/tuition-and-scholarships/entrance-scholarships/",
      "Study in Canada Scholarships (SICS): UG/PG/PhD - Partial - Contact us",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "New Zealand",
    name: "New Zealand",
    slug: "new-zealand",
    flag_url: "🇳🇿",
    description:
      "New Zealand combines a high quality of life with an innovative education system ranked among the best globally. Students benefit from a Post-Study Work Visa of up to 3 years and a safe, welcoming environment.",
    cost_info: "NZD 22,000 – 40,000/year",
    visa_info: "Student Visa via Immigration New Zealand",
    image_url:
      "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800",
    tuition_fees: {
      undergraduate: { min: 22000, max: 40000, currency: "NZ$" },
      postgraduate: { min: 26000, max: 45000, currency: "NZ$" },
      mba: { min: 35000, max: 60000, currency: "NZ$" },
      doctorate: { min: 7000, max: 12000, currency: "NZ$", note: "domestic-equivalent rates for international PhD students" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "90" },
      { test: "PTE", level: "Undergraduate", min_score: "50", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "50", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "50", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "50", max_score: "65" },
    ],
    intakes: [
      {
        name: "February",
        term: "Term 1",
        apply_window: "October - December",
        start_month: "February",
      },
      {
        name: "July",
        term: "Term 2",
        apply_window: "April - May",
        start_month: "July",
      },
    ],
    post_study_work_salary: [
      { field: "IT & Technology", min: 55000, max: 80000, currency: "NZD" },
      { field: "Engineering", min: 55000, max: 78000, currency: "NZD" },
      {
        field: "Healthcare & Nursing",
        min: 60000,
        max: 85000,
        currency: "NZD",
      },
      {
        field: "Business & Management",
        min: 50000,
        max: 72000,
        currency: "NZD",
      },
    ],
    top_courses: [
      "Agriculture & Environmental Science",
      "Computer Science & IT",
      "Engineering",
      "Tourism & Hospitality",
      "Business Administration",
      "Nursing & Healthcare",
      "Film & Creative Arts",
      "Architecture",
      "Data Analytics",
      "Marine Biology",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "New Zealand Commonwealth Scholarships: PG/PhD - Full - https://cscuk.fcdo.gov.uk/apply/new-zealand/",
      "University of Auckland International Student Excellence Scholarship: PhD - Full - https://www.auckland.ac.nz/en/study/scholarships-and-awards/",
      "University of Waikato International Excellence Scholarship: UG - Partial - https://www.waikato.ac.nz/int/study/scholarships/",
      "University of Otago International Scholarships: PG/PhD - Full/Partial - https://www.otago.ac.nz/courses/scholarships/",
      "Auckland University of Technology (AUT) Scholarships: UG/PG - Partial - https://www.aut.ac.nz/study/fees-and-scholarships/",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "Ireland",
    name: "Ireland",
    slug: "ireland",
    flag_url: "🇮🇪",
    description:
      "Ireland is the only English-speaking country in the Eurozone, making it a gateway to Europe's job market. It is home to global tech giants like Google, Meta, and Apple, offering outstanding placement and internship opportunities.",
    cost_info: "EUR 10,000 – 30,000/year",
    visa_info: "Irish Student Visa (C or D) via INIS",
    image_url:
      "https://images.unsplash.com/photo-1564959130747-897fb406b9af?w=800",
    tuition_fees: {
      undergraduate: { min: 10000, max: 30000, currency: "EUR" },
      postgraduate: { min: 11000, max: 35000, currency: "EUR" },
      mba: { min: 15000, max: 38000, currency: "EUR" },
      doctorate: { min: 8000, max: 20000, currency: "EUR" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "90" },
      { test: "PTE", level: "Undergraduate", min_score: "50", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "50", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "50", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "50", max_score: "65" },
    ],
    intakes: [
      {
        name: "Autumn",
        term: "Primary",
        apply_window: "February - June",
        start_month: "September",
      },
      {
        name: "Spring",
        term: "Secondary",
        apply_window: "October - December",
        start_month: "January/February",
      },
    ],
    post_study_work_salary: [
      {
        field: "IT & Computer Science",
        min: 45000,
        max: 70000,
        currency: "EUR",
      },
      {
        field: "Pharma & Biotechnology",
        min: 45000,
        max: 65000,
        currency: "EUR",
      },
      { field: "Finance & Banking", min: 40000, max: 60000, currency: "EUR" },
      {
        field: "Business & Management",
        min: 38000,
        max: 55000,
        currency: "EUR",
      },
    ],
    top_courses: [
      "Computer Science & IT",
      "Pharmaceutical Science",
      "Business & Management",
      "Finance & Accounting",
      "Law",
      "Engineering",
      "Data Analytics",
      "International Business",
      "Healthcare Management",
      "Media & Communications",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrolment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Government of Ireland International Education Scholarship (GOI-IES): PG/PhD - Full - https://hea.ie/policy/internationalisation/goi-ies/",
      "Government of Ireland Postgraduate Scholarship: PG/PhD - Partial - https://research.ie/funding/goipg/",
      "UCD Global Excellence Scholarship: UG/PG - Full/Partial - https://www.ucd.ie/global/study-at-ucd/scholarshipsfinances/",
      "University of Galway International Student Scholarships: UG/PG - Full/Partial - https://www.universityofgalway.ie/internationalscholarships/",
      "TU Dublin Centenary Scholarship: UG/PG - Partial - https://www.tudublin.ie/connect/tu-dublin-foundation/scholarships/",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "Korea",
    name: "South Korea",
    slug: "korea",
    flag_url: "🇰🇷",
    description:
      "South Korea is rapidly emerging as a top Asian study destination, combining cutting-edge technology, K-culture influence, and globally ranked universities like KAIST, POSTECH, and Seoul National University. Generous government scholarships like KGSP make it highly affordable.",
    cost_info: "USD 2,500 – 6,000/year",
    visa_info: "Student Visa (D-2) via Korean Embassy/Consulate",
    image_url:
      "https://images.unsplash.com/photo-1538485399081-7191377e8241?w=800",
    tuition_fees: {
      undergraduate: { min: 2500, max: 6000, currency: "$" },
      postgraduate: { min: 3000, max: 7000, currency: "$" },
      mba: { min: 5000, max: 10000, currency: "$" },
      doctorate: { min: 3000, max: 6000, currency: "$" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "Postgraduate", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "MBA", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "Doctorate", min_score: "5.5", max_score: "6.0" },
      { test: "TOEFL", level: "Undergraduate", min_score: "71", max_score: "80" },
      { test: "TOEFL", level: "Postgraduate", min_score: "71", max_score: "80" },
      { test: "TOEFL", level: "MBA", min_score: "71", max_score: "80" },
      { test: "TOEFL", level: "Doctorate", min_score: "71", max_score: "80" },
      { test: "PTE", level: "Undergraduate", min_score: "50", max_score: "54" },
      { test: "PTE", level: "Postgraduate", min_score: "50", max_score: "54" },
      { test: "PTE", level: "MBA", min_score: "50", max_score: "54" },
      { test: "PTE", level: "Doctorate", min_score: "50", max_score: "54" },
    ],
    intakes: [
      {
        name: "Spring",
        term: "Primary",
        apply_window: "September - November",
        start_month: "March",
      },
      {
        name: "Autumn",
        term: "Secondary",
        apply_window: "March - May",
        start_month: "September",
      },
    ],
    post_study_work_salary: [
      {
        field: "IT & Computer Science",
        min: 35000000,
        max: 55000000,
        currency: "KRW",
      },
      { field: "Engineering", min: 32000000, max: 50000000, currency: "KRW" },
      {
        field: "Business & Management",
        min: 30000000,
        max: 48000000,
        currency: "KRW",
      },
      {
        field: "Education & Research",
        min: 28000000,
        max: 45000000,
        currency: "KRW",
      },
    ],
    top_courses: [
      "Computer Science & AI",
      "Engineering (Mechanical, Electrical)",
      "Business Administration",
      "Korean Language & Culture",
      "International Studies",
      "Biotechnology",
      "Architecture & Design",
      "Film & Media Studies",
      "Economics",
      "Public Health",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate/Apostille",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Global Korea Scholarship (GKS): UG/PG/PhD - Full - https://gksscholarship.com/",
      "GIST Scholarship: PG/PhD - Full - https://www.gist.ac.kr/iadm/html/sub04/0401.html",
      "KAIST Graduate Scholarship: PG - Full/Partial - https://www.gist.ac.kr/iadm/html/sub04/0401.html",
      "SNU GSFS: PG - Full - https://oga.snu.ac.kr/scholarship/graduate-scholarship-for-excellent-foreign-students-gsfs/",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "Malaysia",
    name: "Malaysia",
    slug: "malaysia",
    flag_url: "🇲🇾",
    description:
      "Malaysia is one of Asia's most affordable and diverse study destinations, offering globally recognised degrees through twinning programs with UK and Australian universities. With English as the medium of instruction and a low cost of living, it is ideal for budget-conscious international students.",
    cost_info: "USD 3,500 – 6,000/year",
    visa_info: "Student Pass via Immigration Department of Malaysia (iKad)",
    image_url:
      "/assets/malaysia.jpg",
    tuition_fees: {
      undergraduate: { min: 3500, max: 6000, currency: "$" },
      postgraduate: { min: 4000, max: 7000, currency: "$" },
      mba: { min: 5000, max: 9000, currency: "$" },
      doctorate: { min: 4000, max: 6000, currency: "$" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "Postgraduate", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "MBA", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "Doctorate", min_score: "5.5", max_score: "6.0" },
      { test: "TOEFL", level: "Undergraduate", min_score: "46", max_score: "60" },
      { test: "TOEFL", level: "Postgraduate", min_score: "46", max_score: "60" },
      { test: "TOEFL", level: "MBA", min_score: "46", max_score: "60" },
      { test: "TOEFL", level: "Doctorate", min_score: "46", max_score: "60" },
      { test: "PTE", level: "Undergraduate", min_score: "51", max_score: "58" },
      { test: "PTE", level: "Postgraduate", min_score: "51", max_score: "58" },
      { test: "PTE", level: "MBA", min_score: "51", max_score: "58" },
      { test: "PTE", level: "Doctorate", min_score: "51", max_score: "58" },
    ],
    intakes: [
      {
        name: "March",
        term: "Term 1",
        apply_window: "November - January",
        start_month: "March",
      },
      {
        name: "July",
        term: "Term 2",
        apply_window: "March - May",
        start_month: "July",
      },
      {
        name: "October",
        term: "Term 3",
        apply_window: "July - August",
        start_month: "October",
      },
    ],
    post_study_work_salary: [
      {
        field: "IT & Computer Science",
        min: 36000,
        max: 72000,
        currency: "MYR",
      },
      { field: "Engineering", min: 36000, max: 66000, currency: "MYR" },
      {
        field: "Business & Management",
        min: 30000,
        max: 60000,
        currency: "MYR",
      },
      {
        field: "Hospitality & Tourism",
        min: 24000,
        max: 48000,
        currency: "MYR",
      },
    ],
    top_courses: [
      "Business Administration",
      "Computer Science & IT",
      "Engineering",
      "Hospitality & Tourism Management",
      "Medicine & Healthcare",
      "Accounting & Finance",
      "Architecture",
      "Mass Communication",
      "Biotechnology",
      "Data Science",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Albukhary International University (AIU) Scholarships: UG - Full - https://aiu.edu.my/scholarship/",
      "Malaysia International Scholarship (MIS): PG/PhD - Full - https://biasiswa.mohe.gov.my/INTER/index.php",
      "International Graduate Student Scholarship (IGSS): PhD - Full/Partial - https://sgs.upm.edu.my/financial_assistance_scholarships-1893",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "Finland",
    name: "Finland",
    slug: "finland",
    flag_url: "🇫🇮",
    description: "Finland is known for having one of the world's most successful education systems, pristine nature, and top-tier universities like University of Helsinki and Aalto University.",
    cost_info: "EUR 7,000 – 20,000/year",
    visa_info: "Student Residence Permit via Migri (Finnish Immigration Service)",
    image_url: "https://images.unsplash.com/photo-1517404212738-19266e9017f5?w=800",
    tuition_fees: {
      undergraduate: { min: 7000, max: 20000, currency: "EUR" },
      postgraduate: { min: 7000, max: 30000, currency: "EUR" },
      mba: { min: 15000, max: 38000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "EUR", note: "Mostly funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "95" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      { name: "Joint Application", term: "Autumn Intake", apply_window: "January" },
      { name: "Additional Application", term: "Spring Intake", apply_window: "August - September" },
    ],
    post_study_work_salary: [
      { field: "Software Engineering", min: 38000, max: 55000, currency: "EUR" },
      { field: "Business & Analytics", min: 32000, max: 48000, currency: "EUR" },
    ],
    top_courses: [
      "Information Technology",
      "Business & Entrepreneurship",
      "Environmental Science",
      "Education & Pedagogy",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate/Apostille",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
scholarships: [
      "Erasmus Mundus Scholarships: Full - https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",
      "Aalto University Scholarships: UG/PG - Partial - https://www.aalto.fi/en/admission-services/scholarships-and-tuition-fees",
      "University of Eastern Finland (UEF) Scholarships: UG - Partial - https://www.uef.fi/en/tuition-fees-waivers-and-scholarships",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "Belgium",
    name: "Belgium",
    slug: "belgium",
    flag_url: "🇧🇪",
    description: "Belgium, located in the heart of Europe, hosts highly ranked universities offering diverse English-taught programs and an international environment.",
    cost_info: "EUR 3,000 – 10,000/year",
    visa_info: "Belgian Student Visa (Type D) via Belgian Embassy",
    image_url: "https://images.unsplash.com/photo-1565538810844-1e119fa1112d?w=800",
    tuition_fees: {
      undergraduate: { min: 3000, max: 10000, currency: "EUR" },
      postgraduate: { min: 3000, max: 15000, currency: "EUR" },
      mba: { min: 3000, max: 38000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "EUR", note: "Mostly funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "95" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      { name: "Autumn", term: "Term 1", apply_window: "January - April" },
      { name: "Spring", term: "Term 2", apply_window: "September - November" },
    ],
    post_study_work_salary: [
      { field: "IT & Telecommunications", min: 36000, max: 50000, currency: "EUR" },
      { field: "International Relations", min: 30000, max: 45000, currency: "EUR" },
    ],
    top_courses: [
      "International Relations & Politics",
      "Biomedical Sciences",
      "Business Management",
      "Computer Science",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate/Apostille",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Erasmus Mundus Joint Masters Scholarships: PG - Full - https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",
      "Master Mind Scholarships: PG - Partial - Contact us",
      "KU Leuven Science@Leuven Scholarship: PG - Full/Partial - https://www.kuleuven.be/scholarships/",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "Netherlands",
    name: "Netherlands",
    slug: "netherlands",
    flag_url: "🇳🇱",
    description: "The Netherlands was one of the first non-English-speaking countries to offer English-taught courses. It features top universities, excellent research facilities, and a highly international student body.",
    cost_info: "EUR 10,000 – 20,000/year",
    visa_info: "MVV Entry Visa and VVR Residence Permit via IND",
    image_url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800",
    tuition_fees: {
      undergraduate: { min: 10000, max: 20000, currency: "EUR" },
      postgraduate: { min: 10000, max: 30000, currency: "EUR" },
      mba: { min: 15000, max: 38000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "EUR", note: "Mostly funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "95" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      { name: "September Intake", term: "Semester 1", apply_window: "October - January" },
      { name: "February Intake", term: "Semester 2", apply_window: "June - August" },
    ],
    post_study_work_salary: [
      { field: "Data Science & IT", min: 42000, max: 60000, currency: "EUR" },
      { field: "Engineering & Logistics", min: 38000, max: 55000, currency: "EUR" },
    ],
    top_courses: [
      "Civil & Hydraulic Engineering",
      "Business & Economics",
      "Data Science & AI",
      "Agricultural Studies",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate/Apostille",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Erasmus Mundus Joint Masters Scholarships: PG - Full - https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",
      "NL Scholarship (formerly Holland Scholarship): UG/PG - Partial - https://www.studyinnl.org/finances/nl-scholarship",
      "Maastricht University NL-High Potential Scholarship: PG - Full - https://www.maastrichtuniversity.nl/studeren/toelating-inschrijving/financing-your-studies/scholarships/",
      "TU Delft Excellence Scholarship (Justus & Louise van Effen): PG/PhD - Full - https://www.tudelft.nl/onderwijs/studievoorlichting/praktische-zaken/scholarships",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "Hungary",
    name: "Hungary",
    slug: "hungary",
    flag_url: "🇭🇺",
    description: "Hungary offers affordable tuition and living costs, making it a popular European destination. Home to centuries-old universities and a rich cultural heritage.",
    cost_info: "EUR 3,000 – 15,000/year",
    visa_info: "D-Type Student Visa via Hungarian Consulate",
    image_url: "https://images.unsplash.com/photo-1545259741-0d478f9e23b3?w=800",
    tuition_fees: {
      undergraduate: { min: 3000, max: 12000, currency: "EUR" },
      postgraduate: { min: 3000, max: 15000, currency: "EUR" },
      mba: { min: 5000, max: 25000, currency: "EUR" },
      doctorate: { min: 3000, max: 12000, currency: "EUR" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "4.5", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "4.5", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "5.5", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "5.5", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "41", max_score: "90" },
      { test: "TOEFL", level: "Postgraduate", min_score: "45", max_score: "90" },
      { test: "TOEFL", level: "MBA", min_score: "45", max_score: "90" },
      { test: "TOEFL", level: "Doctorate", min_score: "55", max_score: "90" },
      { test: "PTE", level: "Undergraduate", min_score: "42", max_score: "60" },
      { test: "PTE", level: "Postgraduate", min_score: "42", max_score: "60" },
      { test: "PTE", level: "MBA", min_score: "42", max_score: "60" },
      { test: "PTE", level: "Doctorate", min_score: "42", max_score: "60" },
    ],
    intakes: [
      { name: "September Intake", term: "Fall", apply_window: "April - June" },
      { name: "February Intake", term: "Spring", apply_window: "October - November" },
    ],
    post_study_work_salary: [],
    top_courses: ["Medicine", "Engineering", "IT & Computer Science", "Business"],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Acceptance Letter",
      "Recent Bank Statement",
      "All academic Certificates/ Transcripts/ English Proficiency",
      "Medical Insurance",
      "Tuition Fee Receipt",
    ],
    scholarships: [
      "Erasmus Mundus Joint Masters Scholarships: PG - Full - https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",
      "Stipendium Hungaricum: UG/PG/PhD - Full - https://apply.stipendiumhungaricum.hu",
      "Hungarian Diaspora Scholarship: UG/PG/PhD - Full - https://apply.stipendiumhungaricum.hu",
      "University-specific Scholarships: UG/PG/PhD - Full - Contact us",
    ],
  },
  {
    country: "Sweden",
    name: "Sweden",
    slug: "sweden",
    flag_url: "🇸🇪",
    description: "Sweden is known for its innovative teaching methods, flat hierarchy, and sustainable approach. Home to world-class universities offering numerous English-taught programmes.",
    cost_info: "EUR 8,000 – 18,000/year",
    visa_info: "Residence Permit for Studies via Swedish Migration Agency",
    image_url: "https://images.unsplash.com/photo-1584957113488-2c58eaa4af76?w=800",
    tuition_fees: {
      undergraduate: { min: 8000, max: 18000, currency: "EUR" },
      postgraduate: { min: 8000, max: 20000, currency: "EUR" },
      mba: { min: 15000, max: 35000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "EUR", note: "Mostly funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "95" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      { name: "Autumn Intake", term: "Semester 1", apply_window: "October - January" },
      { name: "Spring Intake", term: "Semester 2", apply_window: "June - August" },
    ],
    post_study_work_salary: [],
    top_courses: ["Engineering", "IT & Computer Science", "Life Sciences", "Business"],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "All academic Certificate/ Transcripts/ English Proficiency",
      "Medical Insurance",
      "Statement of purposes",
    ],
    scholarships: [
      "Erasmus Mundus Joint Master's Degrees: PG - Full - https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",
      "Lund University Global Scholarship: PG - Partial - https://www.lunduniversity.lu.se/study/admission-degree-studies/scholarships-and-awards/",
      "Chalmers University of Technology Scholarships: PG - Partial - https://www.chalmers.se/en/education/your-studies/plan-and-conduct-your-studies/scholarships-for-enrolled-students/",
      "Uppsala University Master's Scholarships: PG - Partial - Contact us",
      "University Specific Scholarships: UG/PG - Full/Partial - Contact us",
    ],
  },
  {
    country: "Norway",
    name: "Norway",
    slug: "norway",
    flag_url: "🇳🇴",
    description: "Norway offers high-quality education with no tuition fees at public universities for all students. Known for its stunning nature, high standard of living, and strong economy.",
    cost_info: "No tuition fees (public universities): living costs ~NOK 120,000/year",
    visa_info: "Student Residence Permit via UDI (Norwegian Directorate of Immigration)",
    image_url: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800",
    tuition_fees: {
      undergraduate: { min: 0, max: 0, currency: "NOK", note: "No tuition fees" },
      postgraduate: { min: 0, max: 0, currency: "NOK", note: "No tuition fees" },
      mba: { min: 15000, max: 35000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "NOK", note: "Fully funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "95" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      { name: "Autumn Intake", term: "Fall", apply_window: "October - March" },
    ],
    post_study_work_salary: [],
    top_courses: ["Engineering", "Marine Biology", "Oil & Gas", "Information Technology"],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Acceptance Letter",
      "Recent Bank Statement (living costs)",
      "All academic Certificate/ Transcripts/ English Proficiency",
      "Housing Contract",
      "Medical Insurance",
    ],
    scholarships: [
      "Erasmus Mundus Joint Masters Scholarships: PG - Full - https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",
      "University of Oslo Scholarships: PG/PhD - Full/Partial - Contact us",
      "Research Council of Norway Scholarships: PhD - Full - https://www.forskningsradet.no/en/financing/what/",
      "University-specific Scholarships: UG/PG/PhD - Full/Partial - Contact us",
    ],
  },
];
