export const countriesFallback = [
  {
    country: "Australia",
    name: "Australia",
    slug: "australia",
    flag_url: "🇦🇺",
    description:
      "Australia is one of the world's most popular study destinations, offering globally recognised qualifications, a multicultural environment, and a Post-Study Work Visa of up to 4 years. It is home to 8 universities ranked in the global top 100.",
    cost_info: "AUD 20,000 – 50,000/year",
    visa_info: "Student Visa (Subclass 500) via Department of Home Affairs",
    image_url:
      "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=800",
    tuition_fees: {
      undergraduate: { min: 20000, max: 50000, currency: "AU$" },
      postgraduate: { min: 22000, max: 55000, currency: "AU$" },
      mba: { min: 30000, max: 70000, currency: "AU$" },
      doctorate: { min: 25000, max: 45000, currency: "AU$" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.0" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.5", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.5", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.5", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "60", max_score: "79" },
      { test: "TOEFL", level: "Postgraduate", min_score: "79", max_score: "94" },
      { test: "TOEFL", level: "MBA", min_score: "79", max_score: "100" },
      { test: "TOEFL", level: "Doctorate", min_score: "79", max_score: "100" },
      { test: "PTE", level: "Undergraduate", min_score: "50", max_score: "58" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "72" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "72" },
    ],
    intakes: [
      { name: "February", term: "Term 1", apply_window: "October - November" },
      { name: "July", term: "Term 2", apply_window: "May - June" },
      { name: "November", term: "Term 3", apply_window: "September" },
    ],
    post_study_work_salary: [
      { field: "IT & Tech", min: 60000, max: 80000, currency: "AUD" },
      {
        field: "Business & Management",
        min: 65000,
        max: 85000,
        currency: "AUD",
      },
      { field: "Health & Medicine", min: 70000, max: 90000, currency: "AUD" },
      { field: "Engineering", min: 65000, max: 88000, currency: "AUD" },
    ],
    top_courses: [
      "Engineering",
      "Business and Management",
      "Information Technology",
      "Environmental Sciences",
      "Tourism and Hospitality",
      "Nursing",
      "STEM Courses",
      "Architecture & Construction",
      "Computer Science",
      "Commercial Pilot",
      "Public Health",
      "Juris Doctor",
      "Culinary Arts",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrolment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Police Clearance",
      "Statement of purposes",
    ],
    scholarships: [
      "Australia Awards: Fully Funded",
      "Endeavour Scholarship: AUD 272,500",
      "University Excellence Awards: 25%–50%",
      "International Merit Scholarships: AUD 5,000–15,000",
    ],
  },
  {
    country: "UK",
    name: "UK",
    slug: "uk",
    flag_url: "🇬🇧",
    description:
      "The United Kingdom is home to some of the world's oldest and most prestigious universities including Oxford, Cambridge, and Imperial College London. The Graduate Route Visa allows 2 years post-study work rights, making it a top choice for career-driven students.",
    cost_info: "GBP 10,000 – 38,000/year",
    visa_info: "UK Student Visa via UKVI (formerly Tier 4)",
    image_url:
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
    tuition_fees: {
      undergraduate: { min: 10000, max: 38000, currency: "£" },
      postgraduate: { min: 10000, max: 42000, currency: "£" },
      mba: { min: 15000, max: 65000, currency: "£" },
      doctorate: { min: 12000, max: 28000, currency: "£" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.5", max_score: "7.0" },
      { test: "IELTS", level: "MBA", min_score: "6.5", max_score: "7.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.5", max_score: "7.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "90", max_score: "100" },
      { test: "TOEFL", level: "MBA", min_score: "95", max_score: "105" },
      { test: "TOEFL", level: "Doctorate", min_score: "95", max_score: "105" },
      { test: "PTE", level: "Undergraduate", min_score: "56", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "61", max_score: "70" },
      { test: "PTE", level: "MBA", min_score: "65", max_score: "76" },
      { test: "PTE", level: "Doctorate", min_score: "65", max_score: "76" },
    ],
    intakes: [
      { name: "Autumn", term: "Term 1", apply_window: "September - December" },
      { name: "Winter", term: "Term 2", apply_window: "January - April" },
      { name: "Spring", term: "Term 3", apply_window: "April - June" },
      { name: "Summer", term: "Term 4", apply_window: "June - August" },
    ],
    post_study_work_salary: [
      {
        field: "Business Management / Statistics & Data Science",
        min: 70000,
        max: 70000,
        currency: "GBP",
      },
      {
        field: "Education and Training",
        min: 45000,
        max: 45000,
        currency: "GBP",
      },
      { field: "Healthcare", min: 51000, max: 51000, currency: "GBP" },
      {
        field: "IT & Computer Science",
        min: 65000,
        max: 65000,
        currency: "GBP",
      },
    ],
    top_courses: [
      "Law",
      "Medicine",
      "Engineering & Technology",
      "Sciences",
      "Architecture",
      "Business and Management",
      "Humanities",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "CAS Letter",
      "Recent Bank Statement",
      "All academic Certificates / Transcripts",
      "English Proficiency Certificate",
      "Tuberculosis Blood (TB) Test",
      "Health Surcharge",
      "Work Experience Letter (if applicable)",
    ],
    scholarships: [
      "Chevening Scholarship: Fully Funded",
      "Commonwealth Scholarship: Fully Funded",
      "GREAT Scholarship: £10,000",
      "University Bursaries: £2,000–£8,000",
    ],
  },
  {
    country: "USA",
    name: "USA",
    slug: "usa",
    flag_url: "🇺🇸",
    description:
      "The United States hosts the world's largest higher education system with over 4,000 accredited institutions. Home to Ivy League universities and Silicon Valley, the USA offers unparalleled research, innovation, and career networking opportunities for international students.",
    cost_info: "USD 8,000 – 75,000/year",
    visa_info: "F-1 Student Visa via US Embassy/Consulate",
    image_url:
      "https://images.unsplash.com/photo-1564309780826-cce2ef0705a0?q=80&w=1170&auto=format&fit=crop",
    tuition_fees: {
      undergraduate: { min: 8000, max: 75000, currency: "$" },
      postgraduate: { min: 8000, max: 80000, currency: "$" },
      mba: { min: 9000, max: 120000, currency: "$" },
      doctorate: { min: 9000, max: 35000, currency: "$" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "5.5", max_score: "7.0" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "7.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "7.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "7.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "55", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "55", max_score: "105" },
      { test: "TOEFL", level: "MBA", min_score: "58", max_score: "105" },
      { test: "TOEFL", level: "Doctorate", min_score: "58", max_score: "105" },
      { test: "PTE", level: "Undergraduate", min_score: "47", max_score: "67" },
      { test: "PTE", level: "Postgraduate", min_score: "52", max_score: "72" },
      { test: "PTE", level: "MBA", min_score: "56", max_score: "78" },
      { test: "PTE", level: "Doctorate", min_score: "56", max_score: "78" },
    ],
    intakes: [
      {
        name: "Fall",
        term: "Primary",
        apply_window: "December - February",
        start_month: "August/September",
      },
      {
        name: "Spring",
        term: "Secondary",
        apply_window: "August - October",
        start_month: "January/February",
      },
      {
        name: "Summer",
        term: "Limited",
        apply_window: "February - March",
        start_month: "May/June",
      },
    ],
    post_study_work_salary: [
      {
        field: "Business Management / Statistics & Data Science",
        min: 70000,
        max: 70000,
        currency: "USD",
      },
      {
        field: "Education and Training",
        min: 45000,
        max: 45000,
        currency: "USD",
      },
      { field: "Healthcare", min: 51000, max: 51000, currency: "USD" },
      {
        field: "IT & Computer Science",
        min: 65000,
        max: 65000,
        currency: "USD",
      },
    ],
    top_courses: [
      "Computer Science and Information Technology",
      "Engineering",
      "Data Science and Analytics",
      "Biotechnology and Life Sciences",
      "MBA",
      "Finance and Banking",
      "International Business",
      "Medicine and Healthcare",
      "Public Health",
      "Pharmacy and Biomedical Sciences",
    ],
    visa_documents: [
      "Passport",
      "I-20 Form from university",
      "DS-160 Application Confirmation Form",
      "SEVIS Payment Confirmation",
      "Bank Solvency proof",
      "All academic Transcripts & Certificates",
      "English Proficiency Certificate / SAT / GRE / GMAT (if applicable)",
    ],
    scholarships: [
      "Fulbright Scholarship: Fully Funded",
      "Hubert Humphrey Fellowship: Fully Funded",
      "University Merit Awards: Up to 50%",
      "OEA Scholarships: Varies",
    ],
  },
  {
    country: "Canada",
    name: "Canada",
    slug: "canada",
    flag_url: "🇨🇦",
    description:
      "Canada offers world-class education, multicultural cities, and one of the most welcoming immigration pathways for international students. With 700+ partner institutions across major provinces, it is a top destination for quality and affordability.",
    cost_info: "CAD 18,000 – 45,000/year",
    visa_info: "Student Direct Stream (SDS) or regular Study Permit via IRCC",
    image_url:
      "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=800",
    tuition_fees: {
      undergraduate: { min: 18000, max: 45000, currency: "CA$" },
      postgraduate: { min: 17000, max: 40000, currency: "CA$" },
      mba: { min: 25000, max: 80000, currency: "CA$" },
      doctorate: { min: 7000, max: 25000, currency: "CA$" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.5", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.5", max_score: "7.0" },
      { test: "IELTS", level: "Doctorate", min_score: "6.5", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Postgraduate", min_score: "88", max_score: "100" },
      { test: "TOEFL", level: "MBA", min_score: "90", max_score: "105" },
      { test: "TOEFL", level: "Doctorate", min_score: "90", max_score: "105" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "60", max_score: "68" },
      { test: "PTE", level: "MBA", min_score: "65", max_score: "76" },
      { test: "PTE", level: "Doctorate", min_score: "65", max_score: "76" },
    ],
    intakes: [
      {
        name: "Fall",
        term: "Primary",
        apply_window: "November - February",
        start_month: "September",
      },
      {
        name: "Winter",
        term: "Secondary",
        apply_window: "August - October",
        start_month: "January",
      },
      {
        name: "Summer",
        term: "Limited",
        apply_window: "February - March",
        start_month: "May",
      },
    ],
    post_study_work_salary: [
      {
        field: "IT & Computer Science",
        min: 65000,
        max: 90000,
        currency: "CAD",
      },
      { field: "Engineering", min: 60000, max: 85000, currency: "CAD" },
      {
        field: "Business & Management",
        min: 55000,
        max: 80000,
        currency: "CAD",
      },
      {
        field: "Healthcare & Nursing",
        min: 65000,
        max: 95000,
        currency: "CAD",
      },
    ],
    top_courses: [
      "Computer Science & IT",
      "Engineering",
      "Business Administration (MBA)",
      "Healthcare & Nursing",
      "Hospitality & Tourism",
      "Environmental Sciences",
      "Finance & Banking",
      "Data Science",
      "Architecture",
      "Public Health",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Enrollment confirmation",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Police Clearence",
      "Statement of purposes",
    ],
    scholarships: [
      "Vanier Canada Graduate Scholarships: CAD 50,000/yr",
      "Banting Postdoctoral Fellowships: CAD 70,000/yr",
      "University of Toronto Award: Up to 40%",
      "Provincial Scholarships: Varies",
    ],
  },
  {
    country: "New Zealand",
    name: "New Zealand",
    slug: "new-zealand",
    flag_url: "🇳🇿",
    description:
      "New Zealand combines a high quality of life with an innovative education system ranked among the best globally. Students benefit from a Post-Study Work Visa of up to 3 years and a safe, welcoming environment.",
    cost_info: "NZD 22,000 – 40,000/year",
    visa_info: "Student Visa via Immigration New Zealand",
    image_url:
      "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800",
    tuition_fees: {
      undergraduate: { min: 22000, max: 40000, currency: "NZ$" },
      postgraduate: { min: 26000, max: 45000, currency: "NZ$" },
      mba: { min: 35000, max: 60000, currency: "NZ$" },
      doctorate: { min: 7000, max: 12000, currency: "NZ$", note: "domestic-equivalent rates for international PhD students" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "90" },
      { test: "PTE", level: "Undergraduate", min_score: "50", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "50", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "50", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "50", max_score: "65" },
    ],
    intakes: [
      {
        name: "February",
        term: "Term 1",
        apply_window: "October - December",
        start_month: "February",
      },
      {
        name: "July",
        term: "Term 2",
        apply_window: "April - May",
        start_month: "July",
      },
    ],
    post_study_work_salary: [
      { field: "IT & Technology", min: 55000, max: 80000, currency: "NZD" },
      { field: "Engineering", min: 55000, max: 78000, currency: "NZD" },
      {
        field: "Healthcare & Nursing",
        min: 60000,
        max: 85000,
        currency: "NZD",
      },
      {
        field: "Business & Management",
        min: 50000,
        max: 72000,
        currency: "NZD",
      },
    ],
    top_courses: [
      "Agriculture & Environmental Science",
      "Computer Science & IT",
      "Engineering",
      "Tourism & Hospitality",
      "Business Administration",
      "Nursing & Healthcare",
      "Film & Creative Arts",
      "Architecture",
      "Data Analytics",
      "Marine Biology",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Manaaki New Zealand Scholarships: Fully Funded",
      "New Zealand Excellence Awards (NZEA): NZD 5,000–20,000",
      "University International Scholarships: Up to 50%",
      "Vice-Chancellor's Scholarships: Varies",
    ],
  },
  {
    country: "Germany",
    name: "Germany",
    slug: "germany",
    flag_url: "🇩🇪",
    description:
      "Germany is famous for tuition-free public universities and world-leading research institutions. As Europe's largest economy, it offers exceptional career prospects after graduation across engineering, technology, and business.",
    cost_info: "EUR 0 – 20,000/year (public unis mostly free)",
    visa_info: "German Student Visa (National Visa D) via German Embassy",
    image_url:
      "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800",
    tuition_fees: {
      undergraduate: {
        min: 0,
        max: 3000,
        currency: "EUR",
        note: "Public universities charge only semester fees",
      },
      postgraduate: {
        min: 0,
        max: 20000,
        currency: "EUR",
        note: "Private universities up to €20,000",
      },
      mba: { min: 10000, max: 30000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "EUR", note: "Mostly funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.0" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.5", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.5", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.5", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "90" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      {
        name: "Winter Semester",
        term: "Primary",
        apply_window: "May - July",
        start_month: "October",
      },
      {
        name: "Summer Semester",
        term: "Secondary",
        apply_window: "November - January",
        start_month: "April",
      },
    ],
    post_study_work_salary: [
      {
        field: "Engineering & Technology",
        min: 45000,
        max: 65000,
        currency: "EUR",
      },
      {
        field: "IT & Computer Science",
        min: 50000,
        max: 70000,
        currency: "EUR",
      },
      {
        field: "Business & Management",
        min: 40000,
        max: 60000,
        currency: "EUR",
      },
      {
        field: "Medicine & Healthcare",
        min: 50000,
        max: 75000,
        currency: "EUR",
      },
    ],
    top_courses: [
      "Engineering (Mechanical, Electrical, Civil)",
      "Computer Science & IT",
      "Business Administration & MBA",
      "Medicine & Healthcare",
      "Natural Sciences",
      "Architecture",
      "Economics & Finance",
      "Data Science & AI",
      "International Relations",
      "Environmental Science",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Blocked Account proof (€11,904)",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate",
      "Medical Test (if applicable)",
      "Health Surcharge / Insurance",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "DAAD Scholarship: Fully Funded + Monthly Stipend",
      "Erasmus+ Scholarships: Fully Funded",
      "Heinrich Böll Scholarships: Varies",
      "Deutschlandstipendium: €300/month",
    ],
  },
  {
    country: "Ireland",
    name: "Ireland",
    slug: "ireland",
    flag_url: "🇮🇪",
    description:
      "Ireland is the only English-speaking country in the Eurozone, making it a gateway to Europe's job market. It is home to global tech giants like Google, Meta, and Apple, offering outstanding placement and internship opportunities.",
    cost_info: "EUR 10,000 – 30,000/year",
    visa_info: "Irish Student Visa (C or D) via INIS",
    image_url:
      "https://images.unsplash.com/photo-1564959130747-897fb406b9af?w=800",
    tuition_fees: {
      undergraduate: { min: 10000, max: 30000, currency: "EUR" },
      postgraduate: { min: 11000, max: 35000, currency: "EUR" },
      mba: { min: 15000, max: 38000, currency: "EUR" },
      doctorate: { min: 8000, max: 20000, currency: "EUR" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "90" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "90" },
      { test: "PTE", level: "Undergraduate", min_score: "50", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "50", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "50", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "50", max_score: "65" },
    ],
    intakes: [
      {
        name: "Autumn",
        term: "Primary",
        apply_window: "February - June",
        start_month: "September",
      },
      {
        name: "Spring",
        term: "Secondary",
        apply_window: "October - December",
        start_month: "January/February",
      },
    ],
    post_study_work_salary: [
      {
        field: "IT & Computer Science",
        min: 45000,
        max: 70000,
        currency: "EUR",
      },
      {
        field: "Pharma & Biotechnology",
        min: 45000,
        max: 65000,
        currency: "EUR",
      },
      { field: "Finance & Banking", min: 40000, max: 60000, currency: "EUR" },
      {
        field: "Business & Management",
        min: 38000,
        max: 55000,
        currency: "EUR",
      },
    ],
    top_courses: [
      "Computer Science & IT",
      "Pharmaceutical Science",
      "Business & Management",
      "Finance & Accounting",
      "Law",
      "Engineering",
      "Data Analytics",
      "International Business",
      "Healthcare Management",
      "Media & Communications",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrolment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Government of Ireland International Education Scholarship: Fully Funded + €10,000 Stipend",
      "Irish Research Council Scholarships: Fully Funded",
      "University Merit Scholarships: Up to 50%",
      "International Student Scholarships: Varies",
    ],
  },
  {
    country: "France",
    name: "France",
    slug: "france",
    flag_url: "🇫🇷",
    description:
      "France is Europe's top higher education destination, offering affordable tuition at prestigious institutions like Sciences Po and INSEAD. With one of the world's largest economies and a vibrant culture, France is ideal for business, arts, and fashion.",
    cost_info: "EUR 3,000 – 20,000/year",
    visa_info: "Long-Stay Student Visa (VLS-TS) via Campus France",
    image_url:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    tuition_fees: {
      undergraduate: {
        min: 2770,
        max: 15000,
        currency: "EUR",
        note: "Public unis from €2,770; private up to €15,000",
      },
      postgraduate: { min: 3770, max: 20000, currency: "EUR" },
      mba: { min: 15000, max: 50000, currency: "EUR" },
    },
    language_requirements: [
      { test: "IELTS", min_score: 6.0, max_score: 6.5 },
      { test: "TOEFL_IBT", min_score: 80 },
      { test: "DELF/DALF (French)", min_score: "B2 level" },
      { test: "TCF", min_score: "B2 level" },
    ],
    intakes: [
      {
        name: "Autumn",
        term: "Primary",
        apply_window: "January - April",
        start_month: "September",
      },
      {
        name: "Spring",
        term: "Secondary",
        apply_window: "September - November",
        start_month: "January",
      },
    ],
    post_study_work_salary: [
      {
        field: "Business & Management",
        min: 38000,
        max: 55000,
        currency: "EUR",
      },
      { field: "Engineering & Tech", min: 40000, max: 60000, currency: "EUR" },
      { field: "Fashion & Luxury", min: 30000, max: 50000, currency: "EUR" },
      { field: "Finance & Banking", min: 42000, max: 62000, currency: "EUR" },
    ],
    top_courses: [
      "Business & Management",
      "Fashion & Luxury Management",
      "Engineering",
      "International Relations",
      "Culinary Arts",
      "Fine Arts & Design",
      "Economics",
      "Computer Science",
      "Political Science",
      "Hospitality Management",
    ],
    visa_documents: [
      "Valid Passport",
      "Pre-acceptance letter via Campus France",
      "Proof of sufficient funds (€615/month)",
      "Proof of accommodation",
      "Health/travel insurance",
      "English or French proficiency certificate",
      "Statement of Purpose (SOP)",
      "Academic transcripts and certificates",
      "Completed visa application form",
    ],
  },
  {
    country: "Singapore",
    name: "Singapore",
    slug: "singapore",
    flag_url: "🇸🇬",
    description:
      "Singapore is Asia's global education hub, home to world-ranked universities and a thriving business ecosystem. Its strategic location, English-medium instruction, and strong job market make it an excellent choice for international students.",
    cost_info: "SGD 20,000 – 40,000/year",
    visa_info: "Student's Pass (STP) via ICA Singapore",
    image_url:
      "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800",
    tuition_fees: {
      undergraduate: { min: 20000, max: 40000, currency: "SGD" },
      postgraduate: { min: 25000, max: 50000, currency: "SGD" },
      mba: { min: 40000, max: 80000, currency: "SGD" },
    },
    language_requirements: [
      { test: "IELTS", min_score: 6.0, max_score: 6.5 },
      { test: "TOEFL_IBT", min_score: 85, max_score: 100 },
      { test: "PTE", min_score: 58 },
    ],
    intakes: [
      {
        name: "August",
        term: "Primary",
        apply_window: "March - May",
        start_month: "August",
      },
      {
        name: "January",
        term: "Secondary",
        apply_window: "September - November",
        start_month: "January",
      },
    ],
    post_study_work_salary: [
      { field: "Finance & Banking", min: 50000, max: 80000, currency: "SGD" },
      {
        field: "IT & Computer Science",
        min: 55000,
        max: 85000,
        currency: "SGD",
      },
      { field: "Engineering", min: 48000, max: 72000, currency: "SGD" },
      {
        field: "Business & Management",
        min: 45000,
        max: 70000,
        currency: "SGD",
      },
    ],
    top_courses: [
      "Business & Finance",
      "Computer Science & IT",
      "Engineering",
      "Data Science & Analytics",
      "Hospitality & Tourism Management",
      "Law",
      "Medicine & Biomedical Sciences",
      "Architecture",
      "Communication & Media",
      "Supply Chain Management",
    ],
    visa_documents: [
      "Valid Passport",
      "Acceptance letter from a registered institution",
      "Completed eForm 16 (Student's Pass application)",
      "Proof of sufficient funds",
      "Medical insurance",
      "English proficiency test scores",
      "Academic transcripts and certificates",
      "Recent passport-sized photographs",
      "Statement of Purpose (SOP)",
    ],
  },
  {
    country: "UAE",
    name: "UAE",
    slug: "uae",
    flag_url: "🇦🇪",
    description:
      "The UAE has rapidly grown into a premier education destination with campuses from world-leading universities in Dubai and Abu Dhabi. Tax-free salaries, a cosmopolitan lifestyle, and proximity to South Asia make it highly attractive.",
    cost_info: "AED 40,000 – 90,000/year",
    visa_info: "Student Residence Visa sponsored by the institution",
    image_url:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    tuition_fees: {
      undergraduate: { min: 40000, max: 80000, currency: "AED" },
      postgraduate: { min: 50000, max: 90000, currency: "AED" },
      mba: { min: 60000, max: 120000, currency: "AED" },
    },
    language_requirements: [
      { test: "IELTS", min_score: 5.5, max_score: 6.5 },
      { test: "TOEFL_IBT", min_score: 61, max_score: 90 },
      { test: "PTE", min_score: 50, max_score: 58 },
    ],
    intakes: [
      {
        name: "September",
        term: "Primary",
        apply_window: "April - July",
        start_month: "September",
      },
      {
        name: "January",
        term: "Secondary",
        apply_window: "October - December",
        start_month: "January",
      },
    ],
    post_study_work_salary: [
      { field: "Finance & Banking", min: 120000, max: 200000, currency: "AED" },
      { field: "Engineering", min: 100000, max: 160000, currency: "AED" },
      {
        field: "IT & Computer Science",
        min: 110000,
        max: 180000,
        currency: "AED",
      },
      {
        field: "Hospitality & Tourism",
        min: 80000,
        max: 140000,
        currency: "AED",
      },
    ],
    top_courses: [
      "Business Administration & MBA",
      "Finance & Banking",
      "Engineering",
      "Computer Science & IT",
      "Hospitality & Tourism Management",
      "Aviation Management",
      "Media & Communications",
      "Architecture",
      "Law",
      "Healthcare Management",
    ],
    visa_documents: [
      "Valid Passport (minimum 6 months validity)",
      "Acceptance letter from a UAE institution",
      "Emirates ID application",
      "Medical fitness certificate",
      "Health insurance",
      "Passport-sized photographs",
      "English proficiency test scores",
      "Academic transcripts and certificates",
      "Proof of sufficient funds",
    ],
  },
  // Add to countriesFallback array:

  // 1. FIX New Zealand slug
  // Change: slug: "new-zealand"
  // To:     slug: "nz"

  {
    country: "Europe",
    name: "Europe",
    slug: "europe",
    flag_url: "🇪🇺",
    description:
      "Europe offers an unmatched diversity of world-class education systems, from the Netherlands to Spain and beyond. Students benefit from the Schengen Area's freedom of movement, affordable tuition at public universities, and rich cultural immersion across 40+ countries.",
    cost_info: "EUR 2,000 – 20,000/year",
    visa_info:
      "Schengen Student Visa / National Long-Stay Visa (varies by country)",
    image_url:
      "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800",
    tuition_fees: {
      undergraduate: {
        min: 2000,
        max: 15000,
        currency: "EUR",
        note: "Varies by country",
      },
      postgraduate: { min: 3000, max: 20000, currency: "EUR" },
      mba: { min: 10000, max: 40000, currency: "EUR" },
    },
    language_requirements: [
      { test: "IELTS", min_score: 6.0, max_score: 7.0 },
      { test: "TOEFL_IBT", min_score: 80, max_score: 100 },
      { test: "PTE", min_score: 55, max_score: 65 },
    ],
    intakes: [
      {
        name: "Autumn",
        term: "Primary",
        apply_window: "February - May",
        start_month: "September",
      },
      {
        name: "Spring",
        term: "Secondary",
        apply_window: "September - November",
        start_month: "February",
      },
    ],
    post_study_work_salary: [
      {
        field: "Engineering & Technology",
        min: 35000,
        max: 60000,
        currency: "EUR",
      },
      {
        field: "IT & Computer Science",
        min: 40000,
        max: 65000,
        currency: "EUR",
      },
      {
        field: "Business & Management",
        min: 35000,
        max: 55000,
        currency: "EUR",
      },
      {
        field: "Healthcare & Medicine",
        min: 38000,
        max: 65000,
        currency: "EUR",
      },
    ],
    top_courses: [
      "Engineering",
      "Business Administration",
      "Computer Science & IT",
      "Medicine & Healthcare",
      "Architecture",
      "International Relations",
      "Economics & Finance",
      "Data Science & AI",
      "Environmental Sciences",
      "Law",
    ],
    visa_documents: [
      "Valid Passport",
      "University Admission Letter",
      "Proof of sufficient funds",
      "Health/travel insurance",
      "Completed visa application form",
      "Biometric passport photos",
      "Language proficiency certificate",
      "Academic transcripts and certificates",
      "Statement of Purpose (SOP)",
    ],
  },
  {
    country: "Korea",
    name: "South Korea",
    slug: "korea",
    flag_url: "🇰🇷",
    description:
      "South Korea is rapidly emerging as a top Asian study destination, combining cutting-edge technology, K-culture influence, and globally ranked universities like KAIST, POSTECH, and Seoul National University. Generous government scholarships like KGSP make it highly affordable.",
    cost_info: "USD 2,500 – 6,000/year",
    visa_info: "Student Visa (D-2) via Korean Embassy/Consulate",
    image_url:
      "https://images.unsplash.com/photo-1538485399081-7191377e8241?w=800",
    tuition_fees: {
      undergraduate: { min: 2500, max: 6000, currency: "$" },
      postgraduate: { min: 3000, max: 7000, currency: "$" },
      mba: { min: 5000, max: 10000, currency: "$" },
      doctorate: { min: 3000, max: 6000, currency: "$" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "Postgraduate", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "MBA", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "Doctorate", min_score: "5.5", max_score: "6.0" },
      { test: "TOEFL", level: "Undergraduate", min_score: "71", max_score: "80" },
      { test: "TOEFL", level: "Postgraduate", min_score: "71", max_score: "80" },
      { test: "TOEFL", level: "MBA", min_score: "71", max_score: "80" },
      { test: "TOEFL", level: "Doctorate", min_score: "71", max_score: "80" },
      { test: "PTE", level: "Undergraduate", min_score: "50", max_score: "54" },
      { test: "PTE", level: "Postgraduate", min_score: "50", max_score: "54" },
      { test: "PTE", level: "MBA", min_score: "50", max_score: "54" },
      { test: "PTE", level: "Doctorate", min_score: "50", max_score: "54" },
    ],
    intakes: [
      {
        name: "Spring",
        term: "Primary",
        apply_window: "September - November",
        start_month: "March",
      },
      {
        name: "Autumn",
        term: "Secondary",
        apply_window: "March - May",
        start_month: "September",
      },
    ],
    post_study_work_salary: [
      {
        field: "IT & Computer Science",
        min: 35000000,
        max: 55000000,
        currency: "KRW",
      },
      { field: "Engineering", min: 32000000, max: 50000000, currency: "KRW" },
      {
        field: "Business & Management",
        min: 30000000,
        max: 48000000,
        currency: "KRW",
      },
      {
        field: "Education & Research",
        min: 28000000,
        max: 45000000,
        currency: "KRW",
      },
    ],
    top_courses: [
      "Computer Science & AI",
      "Engineering (Mechanical, Electrical)",
      "Business Administration",
      "Korean Language & Culture",
      "International Studies",
      "Biotechnology",
      "Architecture & Design",
      "Film & Media Studies",
      "Economics",
      "Public Health",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate/Apostille",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Global Korea Scholarship (GKS): Fully Funded",
      "University Tuition Waivers: 30%–100% Tuition Waiver",
      "Brain Korea 21 (BK21) Research Grants: Varies",
      "International Student Support Grants: Varies",
    ],
  },
  {
    country: "Malaysia",
    name: "Malaysia",
    slug: "malaysia",
    flag_url: "🇲🇾",
    description:
      "Malaysia is one of Asia's most affordable and diverse study destinations, offering globally recognised degrees through twinning programs with UK and Australian universities. With English as the medium of instruction and a low cost of living, it is ideal for budget-conscious international students.",
    cost_info: "USD 3,500 – 6,000/year",
    visa_info: "Student Pass via Immigration Department of Malaysia (iKad)",
    image_url:
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
    tuition_fees: {
      undergraduate: { min: 3500, max: 6000, currency: "$" },
      postgraduate: { min: 4000, max: 7000, currency: "$" },
      mba: { min: 5000, max: 9000, currency: "$" },
      doctorate: { min: 4000, max: 6000, currency: "$" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "Postgraduate", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "MBA", min_score: "5.5", max_score: "6.0" },
      { test: "IELTS", level: "Doctorate", min_score: "5.5", max_score: "6.0" },
      { test: "TOEFL", level: "Undergraduate", min_score: "46", max_score: "60" },
      { test: "TOEFL", level: "Postgraduate", min_score: "46", max_score: "60" },
      { test: "TOEFL", level: "MBA", min_score: "46", max_score: "60" },
      { test: "TOEFL", level: "Doctorate", min_score: "46", max_score: "60" },
      { test: "PTE", level: "Undergraduate", min_score: "51", max_score: "58" },
      { test: "PTE", level: "Postgraduate", min_score: "51", max_score: "58" },
      { test: "PTE", level: "MBA", min_score: "51", max_score: "58" },
      { test: "PTE", level: "Doctorate", min_score: "51", max_score: "58" },
    ],
    intakes: [
      {
        name: "March",
        term: "Term 1",
        apply_window: "November - January",
        start_month: "March",
      },
      {
        name: "July",
        term: "Term 2",
        apply_window: "March - May",
        start_month: "July",
      },
      {
        name: "October",
        term: "Term 3",
        apply_window: "July - August",
        start_month: "October",
      },
    ],
    post_study_work_salary: [
      {
        field: "IT & Computer Science",
        min: 36000,
        max: 72000,
        currency: "MYR",
      },
      { field: "Engineering", min: 36000, max: 66000, currency: "MYR" },
      {
        field: "Business & Management",
        min: 30000,
        max: 60000,
        currency: "MYR",
      },
      {
        field: "Hospitality & Tourism",
        min: 24000,
        max: 48000,
        currency: "MYR",
      },
    ],
    top_courses: [
      "Business Administration",
      "Computer Science & IT",
      "Engineering",
      "Hospitality & Tourism Management",
      "Medicine & Healthcare",
      "Accounting & Finance",
      "Architecture",
      "Mass Communication",
      "Biotechnology",
      "Data Science",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Malaysia International Scholarship (MIS): Fully Funded",
      "Commonwealth Scholarship: Fully Funded",
      "University Academic Excellence Awards: Up to 50% Tuition Waiver",
      "Special Country Bursaries: Varies",
    ],
  },
  {
    country: "China",
    name: "China",
    slug: "china",
    flag_url: "🇨🇳",
    description:
      "China is the world's third most popular destination for international students, with over 300 universities offering English-medium programs. Government scholarships (CSC) and an affordable cost of living make it an increasingly attractive option for students from South Asia and Africa.",
    cost_info: "CNY 20,000 – 60,000/year (approx. USD 2,800 – 8,500)",
    visa_info: "Student Visa (X1/X2) via Chinese Embassy/Consulate",
    image_url:
      "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800",
    tuition_fees: {
      undergraduate: {
        min: 20000,
        max: 50000,
        currency: "CNY",
        note: "≈ USD 2,800–7,000/year",
      },
      postgraduate: {
        min: 25000,
        max: 60000,
        currency: "CNY",
        note: "≈ USD 3,500–8,500/year",
      },
      mba: {
        min: 50000,
        max: 120000,
        currency: "CNY",
        note: "≈ USD 7,000–17,000/year",
      },
      doctorate: {
        min: 20000,
        max: 50000,
        currency: "CNY",
        note: "≈ USD 2,800–7,000/year",
      },
    },
    language_requirements: [
      { test: "IELTS", min_score: 5.5, max_score: 6.5 },
      { test: "TOEFL_IBT", min_score: 61, max_score: 90 },
      {
        test: "HSK (Chinese)",
        min_score: 3,
        note: "Level 3–5 for Chinese-medium programs",
      },
    ],
    intakes: [
      {
        name: "Autumn",
        term: "Primary",
        apply_window: "March - June",
        start_month: "September",
      },
      {
        name: "Spring",
        term: "Secondary",
        apply_window: "October - December",
        start_month: "March",
      },
    ],
    post_study_work_salary: [
      {
        field: "IT & Computer Science",
        min: 150000,
        max: 300000,
        currency: "CNY",
      },
      { field: "Engineering", min: 120000, max: 250000, currency: "CNY" },
      {
        field: "Business & Management",
        min: 100000,
        max: 220000,
        currency: "CNY",
      },
      {
        field: "Education & Research",
        min: 90000,
        max: 180000,
        currency: "CNY",
      },
    ],
    top_courses: [
      "Chinese Language & Culture (HSK)",
      "Medicine (MBBS)",
      "Engineering",
      "Computer Science & AI",
      "Business Administration",
      "International Trade & Economics",
      "Architecture",
      "Biotechnology",
      "Environmental Science",
      "Finance & Banking",
    ],
    visa_documents: [
      "Valid Passport",
      "JW201 or JW202 admission form",
      "University Admission Notice",
      "Completed visa application form (Form V.2013)",
      "Physical examination record for foreigners",
      "Academic transcripts and certificates",
      "English or Chinese proficiency test scores",
      "Passport-sized photographs",
      "Proof of sufficient funds",
    ],
  },
  {
    country: "Japan",
    name: "Japan",
    slug: "japan",
    flag_url: "🇯🇵",
    description:
      "Japan blends world-leading technology, a rich cultural heritage, and globally recognised universities like Tokyo and Osaka. With generous MEXT government scholarships, English-taught programs, and one of Asia's safest environments, Japan is a top destination for ambitious international students.",
    cost_info: "JPY 500,000 – 1,500,000/year (approx. USD 3,300 – 10,000)",
    visa_info: "College Student Visa (留学) via Japanese Embassy/Consulate",
    image_url:
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    tuition_fees: {
      undergraduate: {
        min: 535800,
        max: 1200000,
        currency: "JPY",
        note: "≈ USD 3,600–8,000/year",
      },
      postgraduate: {
        min: 535800,
        max: 1500000,
        currency: "JPY",
        note: "≈ USD 3,600–10,000/year",
      },
      mba: {
        min: 1000000,
        max: 3000000,
        currency: "JPY",
        note: "≈ USD 6,700–20,000/year",
      },
      doctorate: {
        min: 535800,
        max: 1200000,
        currency: "JPY",
        note: "≈ USD 3,600–8,000/year",
      },
    },
    language_requirements: [
      { test: "IELTS", min_score: 5.5, max_score: 6.5 },
      { test: "TOEFL_IBT", min_score: 61, max_score: 90 },
      {
        test: "JLPT (Japanese)",
        min_score: "N2",
        note: "Required for Japanese-medium programs",
      },
    ],
    intakes: [
      {
        name: "April",
        term: "Primary",
        apply_window: "September - December",
        start_month: "April",
      },
      {
        name: "October",
        term: "Secondary",
        apply_window: "April - June",
        start_month: "October",
      },
    ],
    post_study_work_salary: [
      {
        field: "IT & Computer Science",
        min: 3500000,
        max: 6000000,
        currency: "JPY",
      },
      { field: "Engineering", min: 3200000, max: 5500000, currency: "JPY" },
      {
        field: "Business & Management",
        min: 3000000,
        max: 5000000,
        currency: "JPY",
      },
      {
        field: "Education & Research",
        min: 2800000,
        max: 4500000,
        currency: "JPY",
      },
    ],
    top_courses: [
      "Engineering (Robotics, Mechanical, Electrical)",
      "Computer Science & AI",
      "Business Administration",
      "Japanese Language & Linguistics",
      "Architecture & Design",
      "Medicine & Biomedical Sciences",
      "International Studies",
      "Environmental Science",
      "Anime & Game Design",
      "Economics & Finance",
    ],
    visa_documents: [
      "Valid Passport",
      "Certificate of Eligibility (CoE) issued by JASSO or university",
      "Completed visa application form",
      "Passport-sized photographs",
      "Academic transcripts and certificates",
      "English or Japanese proficiency test scores",
      "Proof of sufficient funds",
      "Health insurance",
      "Statement of Purpose (SOP)",
    ],
  },
  {
    country: "Finland",
    name: "Finland",
    slug: "finland",
    flag_url: "🇫🇮",
    description: "Finland is known for having one of the world's most successful education systems, pristine nature, and top-tier universities like University of Helsinki and Aalto University.",
    cost_info: "EUR 7,000 – 20,000/year",
    visa_info: "Student Residence Permit via Migri (Finnish Immigration Service)",
    image_url: "https://images.unsplash.com/photo-1517404212738-19266e9017f5?w=800",
    tuition_fees: {
      undergraduate: { min: 7000, max: 20000, currency: "EUR" },
      postgraduate: { min: 7000, max: 30000, currency: "EUR" },
      mba: { min: 15000, max: 38000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "EUR", note: "Mostly funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "95" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      { name: "Joint Application", term: "Autumn Intake", apply_window: "January" },
      { name: "Additional Application", term: "Spring Intake", apply_window: "August - September" },
    ],
    post_study_work_salary: [
      { field: "Software Engineering", min: 38000, max: 55000, currency: "EUR" },
      { field: "Business & Analytics", min: 32000, max: 48000, currency: "EUR" },
    ],
    top_courses: [
      "Information Technology",
      "Business & Entrepreneurship",
      "Environmental Science",
      "Education & Pedagogy",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate/Apostille",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Finland Scholarship: €5,000 Relocation Grant + Tuition Waiver",
      "EDUFI Fellowship: Fully Funded",
      "University Tuition Fee Scholarships: 50%–100% Tuition Waiver",
      "Excellence Scholarships: Varies",
    ],
  },
  {
    country: "Denmark",
    name: "Denmark",
    slug: "denmark",
    flag_url: "🇩🇰",
    description: "Denmark offers high-quality education in a safe, friendly, and innovative environment. Renowned for its student-centered learning and green initiatives.",
    cost_info: "EUR 10,000 – 20,000/year",
    visa_info: "Danish Student Residence Permit (ST1) via SIRI",
    image_url: "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
    tuition_fees: {
      undergraduate: { min: 10000, max: 20000, currency: "EUR" },
      postgraduate: { min: 10000, max: 30000, currency: "EUR" },
      mba: { min: 15000, max: 38000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "EUR", note: "Mostly funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "95" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      { name: "Autumn", term: "Term 1", apply_window: "January - March" },
      { name: "Spring", term: "Term 2", apply_window: "August - October" },
    ],
    post_study_work_salary: [
      { field: "Engineering & Tech", min: 45000, max: 65000, currency: "EUR" },
      { field: "Life Sciences & Pharma", min: 48000, max: 70000, currency: "EUR" },
    ],
    top_courses: [
      "Renewable Energy Engineering",
      "Design & Architecture",
      "Environmental Policy",
      "Business & Economics",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate/Apostille",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Danish Government Scholarships: Fully Funded / Full or Partial Tuition Waiver",
      "Erasmus+ Scholarships: Fully Funded",
      "University Merit Scholarships: 50%–100% Tuition Waiver",
      "Nordplus Scholarship: Varies",
    ],
  },
  {
    country: "Belgium",
    name: "Belgium",
    slug: "belgium",
    flag_url: "🇧🇪",
    description: "Belgium, located in the heart of Europe, hosts highly ranked universities offering diverse English-taught programs and an international environment.",
    cost_info: "EUR 3,000 – 10,000/year",
    visa_info: "Belgian Student Visa (Type D) via Belgian Embassy",
    image_url: "https://images.unsplash.com/photo-1565538810844-1e119fa1112d?w=800",
    tuition_fees: {
      undergraduate: { min: 3000, max: 10000, currency: "EUR" },
      postgraduate: { min: 3000, max: 15000, currency: "EUR" },
      mba: { min: 3000, max: 38000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "EUR", note: "Mostly funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "95" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      { name: "Autumn", term: "Term 1", apply_window: "January - April" },
      { name: "Spring", term: "Term 2", apply_window: "September - November" },
    ],
    post_study_work_salary: [
      { field: "IT & Telecommunications", min: 36000, max: 50000, currency: "EUR" },
      { field: "International Relations", min: 30000, max: 45000, currency: "EUR" },
    ],
    top_courses: [
      "International Relations & Politics",
      "Biomedical Sciences",
      "Business Management",
      "Computer Science",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate/Apostille",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "ARES Scholarships: Fully Funded",
      "VLIR-UOS Scholarships: Fully Funded",
      "Master Mind Scholarships: €10,000 + Tuition Waiver",
      "University Excellence Scholarships: Varies",
    ],
  },
  {
    country: "Netherlands",
    name: "Netherlands",
    slug: "netherlands",
    flag_url: "🇳🇱",
    description: "The Netherlands was one of the first non-English-speaking countries to offer English-taught courses. It features top universities, excellent research facilities, and a highly international student body.",
    cost_info: "EUR 10,000 – 20,000/year",
    visa_info: "MVV Entry Visa and VVR Residence Permit via IND",
    image_url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800",
    tuition_fees: {
      undergraduate: { min: 10000, max: 20000, currency: "EUR" },
      postgraduate: { min: 10000, max: 30000, currency: "EUR" },
      mba: { min: 15000, max: 38000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "EUR", note: "Mostly funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "95" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      { name: "September Intake", term: "Semester 1", apply_window: "October - January" },
      { name: "February Intake", term: "Semester 2", apply_window: "June - August" },
    ],
    post_study_work_salary: [
      { field: "Data Science & IT", min: 42000, max: 60000, currency: "EUR" },
      { field: "Engineering & Logistics", min: 38000, max: 55000, currency: "EUR" },
    ],
    top_courses: [
      "Civil & Hydraulic Engineering",
      "Business & Economics",
      "Data Science & AI",
      "Agricultural Studies",
    ],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "Sources of incomes' documents",
      "Tax documentation",
      "All academic Certificate/ Transcripts/ English Proficiency Certificate/Apostille",
      "Medical Test",
      "Health Surcharge",
      "Work Experience Letter",
      "Statement of purposes",
    ],
    scholarships: [
      "Holland Scholarship: €5,000",
      "Orange Knowledge Programme (OKP): Fully Funded",
      "University Excellence Scholarships: 50%–100% Tuition Waiver",
      "International Merit Scholarships: Varies",
    ],
  },
  {
    country: "Hungary",
    name: "Hungary",
    slug: "hungary",
    flag_url: "🇭🇺",
    description: "Hungary offers affordable tuition and living costs, making it a popular European destination. Home to centuries-old universities and a rich cultural heritage.",
    cost_info: "EUR 3,000 – 15,000/year",
    visa_info: "D-Type Student Visa via Hungarian Consulate",
    image_url: "",
    tuition_fees: {
      undergraduate: { min: 3000, max: 12000, currency: "EUR" },
      postgraduate: { min: 3000, max: 15000, currency: "EUR" },
      mba: { min: 5000, max: 25000, currency: "EUR" },
      doctorate: { min: 3000, max: 12000, currency: "EUR" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "4.5", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "4.5", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "5.5", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "5.5", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "41", max_score: "90" },
      { test: "TOEFL", level: "Postgraduate", min_score: "45", max_score: "90" },
      { test: "TOEFL", level: "MBA", min_score: "45", max_score: "90" },
      { test: "TOEFL", level: "Doctorate", min_score: "55", max_score: "90" },
      { test: "PTE", level: "Undergraduate", min_score: "42", max_score: "60" },
      { test: "PTE", level: "Postgraduate", min_score: "42", max_score: "60" },
      { test: "PTE", level: "MBA", min_score: "42", max_score: "60" },
      { test: "PTE", level: "Doctorate", min_score: "42", max_score: "60" },
    ],
    intakes: [
      { name: "September Intake", term: "Fall", apply_window: "April - June" },
      { name: "February Intake", term: "Spring", apply_window: "October - November" },
    ],
    post_study_work_salary: [],
    top_courses: ["Medicine", "Engineering", "IT & Computer Science", "Business"],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Acceptance Letter",
      "Recent Bank Statement",
      "All academic Certificates/ Transcripts/ English Proficiency",
      "Medical Insurance",
      "Tuition Fee Receipt",
    ],
    scholarships: [
      "Stipendium Hungaricum: Fully Funded",
      "University Merit Scholarships: 50%–100% Tuition Waiver",
    ],
  },
  {
    country: "Sweden",
    name: "Sweden",
    slug: "sweden",
    flag_url: "🇸🇪",
    description: "Sweden is known for its innovative teaching methods, flat hierarchy, and sustainable approach. Home to world-class universities offering numerous English-taught programmes.",
    cost_info: "EUR 8,000 – 18,000/year",
    visa_info: "Residence Permit for Studies via Swedish Migration Agency",
    image_url: "",
    tuition_fees: {
      undergraduate: { min: 8000, max: 18000, currency: "EUR" },
      postgraduate: { min: 8000, max: 20000, currency: "EUR" },
      mba: { min: 15000, max: 35000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "EUR", note: "Mostly funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "95" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      { name: "Autumn Intake", term: "Semester 1", apply_window: "October - January" },
      { name: "Spring Intake", term: "Semester 2", apply_window: "June - August" },
    ],
    post_study_work_salary: [],
    top_courses: ["Engineering", "IT & Computer Science", "Life Sciences", "Business"],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Confirmation of Enrollment (CoE)",
      "Recent Bank Statement",
      "All academic Certificate/ Transcripts/ English Proficiency",
      "Medical Insurance",
      "Statement of purposes",
    ],
    scholarships: [
      "Swedish Institute Scholarships: Fully Funded",
      "University Tuition Fee Scholarships: 25%–100% Tuition Waiver",
    ],
  },
  {
    country: "Norway",
    name: "Norway",
    slug: "norway",
    flag_url: "🇳🇴",
    description: "Norway offers high-quality education with no tuition fees at public universities for all students. Known for its stunning nature, high standard of living, and strong economy.",
    cost_info: "No tuition fees (public universities): living costs ~NOK 120,000/year",
    visa_info: "Student Residence Permit via UDI (Norwegian Directorate of Immigration)",
    image_url: "",
    tuition_fees: {
      undergraduate: { min: 0, max: 0, currency: "NOK", note: "No tuition fees" },
      postgraduate: { min: 0, max: 0, currency: "NOK", note: "No tuition fees" },
      mba: { min: 15000, max: 35000, currency: "EUR" },
      doctorate: { min: 0, max: 0, currency: "NOK", note: "Fully funded" },
    },
    language_requirements: [
      { test: "IELTS", level: "Undergraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Postgraduate", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "MBA", min_score: "6.0", max_score: "6.5" },
      { test: "IELTS", level: "Doctorate", min_score: "6.0", max_score: "6.5" },
      { test: "TOEFL", level: "Undergraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Postgraduate", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "MBA", min_score: "80", max_score: "95" },
      { test: "TOEFL", level: "Doctorate", min_score: "80", max_score: "95" },
      { test: "PTE", level: "Undergraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Postgraduate", min_score: "58", max_score: "65" },
      { test: "PTE", level: "MBA", min_score: "58", max_score: "65" },
      { test: "PTE", level: "Doctorate", min_score: "58", max_score: "65" },
    ],
    intakes: [
      { name: "Autumn Intake", term: "Fall", apply_window: "October - March" },
    ],
    post_study_work_salary: [],
    top_courses: ["Engineering", "Marine Biology", "Oil & Gas", "Information Technology"],
    visa_documents: [
      "Online Application",
      "Valid Passport",
      "Acceptance Letter",
      "Recent Bank Statement (living costs)",
      "All academic Certificate/ Transcripts/ English Proficiency",
      "Housing Contract",
      "Medical Insurance",
    ],
    scholarships: [
      "Quota Scheme: Fully Funded (discontinued for new students)",
      "Erasmus+: Fully Funded",
      "University Merit Scholarships: Varies",
    ],
  },
];

