export const countriesFallback = [
  {
    country: "Australia",
    image_url:
      "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=800",
    tuition_fees: {
      undergraduate: { min: 20000, max: 35000, currency: "AUD" },
      postgraduate: { min: 25000, max: 40000, currency: "AUD" },
      doctorate: { min: 18000, max: 32000, currency: "AUD" },
    },
    language_requirements: [
      { test: "IELTS", min_score: 6.5 },
      { test: "TOEFL_IBT", min_score: 79 },
      { test: "PTE", min_score: 58 },
      { test: "CAE", min_score: 169 },
    ],
    intakes: [
      { name: "February", term: "Term 1", apply_window: "October - November" },
      { name: "July", term: "Term 2", apply_window: "May - June" },
      { name: "November", term: "Term 3", apply_window: "September" },
    ],
    post_study_work_salary: [
      { field: "IT & Tech", min: 60000, max: 80000, currency: "AUD" },
      {
        field: "Business & Management",
        min: 65000,
        max: 85000,
        currency: "AUD",
      },
      { field: "Health & Medicine", min: 70000, max: 90000, currency: "AUD" },
      { field: "Engineering", min: 65000, max: 88000, currency: "AUD" },
    ],
    top_courses: [
      "Engineering",
      "Business and Management",
      "Information Technology",
      "Environmental Sciences",
      "Tourism and Hospitality",
      "Nursing",
      "STEM Courses",
      "Architecture & Construction",
      "Computer Science",
      "Commercial Pilot",
      "Public Health",
      "Juris Doctor",
      "Culinary Arts",
    ],
    visa_documents: [
      "Valid Passport",
      "Confirmation of Enrolment (CoE)",
      "GS Statement (Genuine Student Statement)",
      "Proof of sufficient funds",
      "Overseas Student Health Cover (OSHC)",
      "English proficiency proof",
      "Recent passport-sized photographs",
      "Statement of Purpose (SOP)",
      "Academic and work experience documents",
    ],
  },
  {
    country: "UK",
    image_url:
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
    tuition_fees: {
      undergraduate: { min: 12000, max: 35000, currency: "GBP" },
      postgraduate: { min: 12000, max: 35000, currency: "GBP" },
      mba: { min: 13000, max: 60000, currency: "GBP" },
    },
    language_requirements: [
      { test: "IELTS", min_score: 6.0, max_score: 7.5 },
      { test: "TOEFL_IBT", min_score: 80, max_score: 100 },
      { test: "PTE", min_score: 51, max_score: 67 },
    ],
    intakes: [
      { name: "Autumn", term: "Term 1", apply_window: "September - December" },
      { name: "Winter", term: "Term 2", apply_window: "January - April" },
      { name: "Spring", term: "Term 3", apply_window: "April - June" },
      { name: "Summer", term: "Term 4", apply_window: "June - August" },
    ],
    post_study_work_salary: [
      {
        field: "Business Management / Statistics & Data Science",
        min: 70000,
        max: 70000,
        currency: "GBP",
      },
      {
        field: "Education and Training",
        min: 45000,
        max: 45000,
        currency: "GBP",
      },
      { field: "Healthcare", min: 51000, max: 51000, currency: "GBP" },
      {
        field: "IT & Computer Science",
        min: 65000,
        max: 65000,
        currency: "GBP",
      },
    ],
    top_courses: [
      "Law",
      "Medicine",
      "Engineering & Technology",
      "Sciences",
      "Architecture",
      "Business and Management",
      "Humanities",
    ],
    visa_documents: [
      "Valid Passport",
      "Confirmation of Acceptance for Studies (CAS)",
      "Proof of sufficient funds",
      "TB Test Result",
      "Statement of Purpose (SOP)",
      "Academic certificates and transcripts",
    ],
  },
  {
    country: "USA",
    image_url:
      "https://images.unsplash.com/photo-1564309780826-cce2ef0705a0?q=80&w=1170&auto=format&fit=crop",
    tuition_fees: {
      undergraduate: {
        min: 25000,
        max: 50000,
        currency: "USD",
        note: "Private universities",
      },
      postgraduate: {
        min: 30000,
        max: 60000,
        currency: "USD",
        note: "Private universities",
      },
      mba: {
        min: 50000,
        max: 100000,
        currency: "USD",
        note: "Private universities",
      },
      doctorate: {
        min: 40000,
        max: 70000,
        currency: "USD",
        note: "Private universities",
      },
    },
    language_requirements: [
      { test: "IELTS", level: "undergraduate", min_score: 6.0, max_score: 7.0 },
      { test: "IELTS", level: "postgraduate", min_score: 6.5, max_score: 7.5 },
      {
        test: "TOEFL_IBT",
        level: "undergraduate",
        min_score: 61,
        max_score: 83,
      },
      {
        test: "TOEFL_IBT",
        level: "postgraduate",
        min_score: 78,
        max_score: 100,
      },
    ],
    intakes: [
      {
        name: "Fall",
        term: "Primary",
        apply_window: "December - February",
        start_month: "August/September",
      },
      {
        name: "Spring",
        term: "Secondary",
        apply_window: "August - October",
        start_month: "January/February",
      },
      {
        name: "Summer",
        term: "Limited",
        apply_window: "February - March",
        start_month: "May/June",
      },
    ],
    post_study_work_salary: [
      {
        field: "Technology and Software Development",
        note: "Highest demand",
        currency: "USD",
      },
      { field: "Finance and Banking", currency: "USD" },
      { field: "Healthcare and Medical Research", currency: "USD" },
      { field: "Engineering", currency: "USD" },
      { field: "Business Analytics and Data Science", currency: "USD" },
    ],
    top_courses: [
      "Computer Science and Information Technology",
      "Engineering",
      "Data Science and Analytics",
      "Biotechnology and Life Sciences",
      "MBA",
      "Finance and Banking",
      "International Business",
      "Medicine and Healthcare",
      "Public Health",
      "Pharmacy and Biomedical Sciences",
    ],
    visa_documents: [
      "Valid Passport",
      "Form I-20 from university",
      "SEVIS fee payment proof",
      "Financial documents",
      "English proficiency test scores",
      "Standardized test scores (SAT/ACT/GRE/GMAT)",
      "Statement of Purpose (SOP)",
      "Letters of Recommendation (2-3)",
      "Academic transcripts and certificates",
    ],
  },
];
